@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Aug 13 22:06:06 +0200 2025
REM SW Build 4029153 on Fri Oct 13 20:14:34 MDT 2023
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim SPA_top_TB_behav -key {Behavioral:sim_1:Functional:SPA_top_TB} -tclbatch SPA_top_TB.tcl -view D:/Vivado_files/Master_thesis/LDPC_SPA_v42/LDPC_SPA_v42.srcs/sim_1/imports/LDPC_SPA_v17_1/check_node_tb_behav1.wcfg -log simulate.log"
call xsim  SPA_top_TB_behav -key {Behavioral:sim_1:Functional:SPA_top_TB} -tclbatch SPA_top_TB.tcl -view D:/Vivado_files/Master_thesis/LDPC_SPA_v42/LDPC_SPA_v42.srcs/sim_1/imports/LDPC_SPA_v17_1/check_node_tb_behav1.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
