# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Eclypse-Z7-Master.xdc

# IP: ip/float_to_fixed/float_to_fixed.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==float_to_fixed || ORIG_REF_NAME==float_to_fixed} -quiet] -quiet
