# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Vivado_files/Master_thesis/LDPC_SPA_v37/LDPC_SPA_v37.srcs/sources_1/ip/float2fixed_idx/float2fixed_idx.xci
# IP: The module: 'float2fixed_idx' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_files/Master_thesis/LDPC_SPA_v37/LDPC_SPA_v37.gen/sources_1/ip/float2fixed_idx/float2fixed_idx_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'float2fixed_idx'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/Vivado_files/Master_thesis/LDPC_SPA_v37/LDPC_SPA_v37.srcs/sources_1/ip/float2fixed_idx/float2fixed_idx.xci
# IP: The module: 'float2fixed_idx' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_files/Master_thesis/LDPC_SPA_v37/LDPC_SPA_v37.gen/sources_1/ip/float2fixed_idx/float2fixed_idx_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'float2fixed_idx'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
