# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Vivado_files/Master_thesis/LDPC_SPA_v33/LDPC_SPA_v33.srcs/sources_1/ip/tanh_mem/tanh_mem.xci
# IP: The module: 'tanh_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_files/Master_thesis/LDPC_SPA_v33/LDPC_SPA_v33.gen/sources_1/ip/tanh_mem/tanh_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tanh_mem'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Vivado_files/Master_thesis/LDPC_SPA_v33/LDPC_SPA_v33.srcs/sources_1/ip/tanh_mem/tanh_mem.xci
# IP: The module: 'tanh_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_files/Master_thesis/LDPC_SPA_v33/LDPC_SPA_v33.gen/sources_1/ip/tanh_mem/tanh_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tanh_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
