# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Vivado_files/Master_thesis/LDPC_SPA_v37/LDPC_SPA_v37.srcs/sources_1/ip/Lji_mem_bram/Lji_mem_bram.xci
# IP: The module: 'Lji_mem_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_files/Master_thesis/LDPC_SPA_v37/LDPC_SPA_v37.gen/sources_1/ip/Lji_mem_bram/Lji_mem_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lji_mem_bram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Vivado_files/Master_thesis/LDPC_SPA_v37/LDPC_SPA_v37.srcs/sources_1/ip/Lji_mem_bram/Lji_mem_bram.xci
# IP: The module: 'Lji_mem_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_files/Master_thesis/LDPC_SPA_v37/LDPC_SPA_v37.gen/sources_1/ip/Lji_mem_bram/Lji_mem_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lji_mem_bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
