# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Vivado_files/Master_thesis/LDPC_SPA_v17_1/LDPC_SPA_v17_1.srcs/sources_1/ip/fixed2float/fixed2float.xci
# IP: The module: 'fixed2float' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_files/Master_thesis/LDPC_SPA_v17_1/LDPC_SPA_v17_1.gen/sources_1/ip/fixed2float/fixed2float_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fixed2float'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/Vivado_files/Master_thesis/LDPC_SPA_v17_1/LDPC_SPA_v17_1.srcs/sources_1/ip/fixed2float/fixed2float.xci
# IP: The module: 'fixed2float' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_files/Master_thesis/LDPC_SPA_v17_1/LDPC_SPA_v17_1.gen/sources_1/ip/fixed2float/fixed2float_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fixed2float'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
