# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Vivado_files/Master_thesis/LDPC_SPA_v29/LDPC_SPA_v29.srcs/sources_1/ip/hcol_pos_mem/hcol_pos_mem.xci
# IP: The module: 'hcol_pos_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_files/Master_thesis/LDPC_SPA_v29/LDPC_SPA_v29.gen/sources_1/ip/hcol_pos_mem/hcol_pos_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hcol_pos_mem'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Vivado_files/Master_thesis/LDPC_SPA_v29/LDPC_SPA_v29.srcs/sources_1/ip/hcol_pos_mem/hcol_pos_mem.xci
# IP: The module: 'hcol_pos_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_files/Master_thesis/LDPC_SPA_v29/LDPC_SPA_v29.gen/sources_1/ip/hcol_pos_mem/hcol_pos_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hcol_pos_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
